touchlab/KMMBridge

kmmbridge/build.gradle.kts

I used to be able to pass `-PRELEASE_SIGNING_ENABLED=false` to skip signing when doing a local publish for testing. With the gradle plugin publishing changes, that stopped working.
This is a kludgy way to make it work again, but cc @TadeasKriz if you know a better way to do it.

Don't sign if RELEASE_SIGNING_ENABLED=false

---

kmmbridge/src/main/kotlin/KMMBridge.kt
kmmbridge/src/main/kotlin/KmmBridgeExtension.kt
kmmbridge/src/main/kotlin/dependencymanager/SpmDependencyManager.kt

Use framework name from extension when making the package.swift file instead of the project name, remove packageName param to spm

Allow different framework name without extra config

---

.github/workflows/integration-tests.yml

This is a workflow that calls out to other repos where our integration tests live. Right now there's one test case with `githubReleaseArtifacts()` and one with `mavenPublishArtifacts()`.
I left notes for how to add a new test case in the readme at https://github.com/touchlab/KmmBridgeIntegrationTest but there's probably a better place to put them once we're ready to merge this.

PoC Integration Test workflow

---

kmmbridge/src/main/kotlin/KmmBridgeExtension.kt
kmmbridge/src/main/kotlin/dependencymanager/SpmDependencyManager.kt

This should help with #129 
Will need some docs etc as followup. This is a somewhat dangerous thing to do because if you don't push your package file manually later, you can't consume the binary.

Split SPM git operations into a separate task which can be disabled

---

.github/workflows/integration-tests-local-branch-ok.yml
gradle.properties
kmmbridge/src/main/kotlin/KMMBridge.kt
kmmbridge/src/main/kotlin/KmmBridgeExtension.kt
kmmbridge/src/main/kotlin/dependencymanager/SpmDependencyManager.kt
kmmbridge/src/main/kotlin/localdevmanager/LocalDevManager.kt

SPM local dev flow breaks on fix for local branch. Pulled out `LocalDevManager` abstraction to keep basic separation of concerns, but kept implementation in the `SpmDependencyManager` class for simplicity. We'll be moving this out of KMMBridge soon (likely), so a deeper refactor seemed kind of pointless.

SPM local dev flow works for local branch

---

website/docs/spm/01_IOS_SPM.md

Issue: https://github.com/touchlab/Faktory/issues/319
Add info about the commitManually parameter to the website docs.

[Issue-Faktory#319] Add mention of `commitManually` parameter in docs

---

website/docs/spm/01_IOS_SPM.md

Issue: https://github.com/touchlab/Faktory/issues/320
Add info about using spm without cocoapods plugin to the website.

[Issue-faktory#320] Clarify documentation when not including cocoapods plugin

---

website/docs/ciconfig/01_GITHUB_ACTIONS.md

Issue: https://github.com/touchlab/KMMBridge/issues/179
We added the ability to pass custom credentials in https://github.com/touchlab/KMMBridgeGithubWorkflow/pull/3/files
We describe usage of this on the Artifactory docs page, but we should also mention this in the docs page on CI.

[Issue-#179] Document passing custom netrc credentials to github workflow

---

kmmbridge/src/main/kotlin/KmmBridgeExtension.kt
website/docs/cocoapods/03_COCOAPODS_GITHUB_PODSPEC.md

Closes #112
This will run the correct pod command but I haven't tested it end-to-end by actually publishing anything.

Add the ability to publish podspecs to trunk instead of a private spec repo

---

kmmbridge/src/main/kotlin/BuildFileHelper.kt
kmmbridge/src/main/kotlin/ProjectExtensions.kt

Issue: https://github.com/touchlab/KMMBridge/issues/54
Passing in the whole url, or presumably just the repo and not owner, will result in weird error messages.
The goal is to improve error messaging when an invalid value is passed which informs them that the input must be "Owner/Repo"
Added regex check for valid options for setting a github repo (such as url and ssh path), if regex is not matched, exception is thrown.
Tested in KmmBridgeKickStart app by calling `./gradlew kmmBridgePublish -PGITHUB_PUBLISH_TOKEN="$MY_TOKEN" -PGITHUB_REPO="https://github.com/touchlab/KMMBridgeKockStart.git" -PGITHUB_PUBLISH_USER="Touchlab-Bot" --no-daemon --stacktrace`

[#54] Check GITHUB_REPO arg to make sure it's just owner/repo

---

website/docs/general/ANDROID_VERSIONING.md

Fixes #154 
Improve clarity on how KMMBridge's version managers interact (or don't) with android publishing

Documentation on android versions

---

.github/workflows/integration-test-manual-version.yml

Issue: https://github.com/touchlab/KMMBridge/issues/269
Create integration test for using manual version to publish an artifact and confirm it exists. Confirm that if you try to publish the same version twice it fails. Confirm that if you increment the version manually it works
This will require some expansion of the existing integration test functionality because there currently isn't a hook we can use to set the new version as part of the CI flow.

[Issue-269] Test Manual Version Manager

---

website/docs/DEFAULT_GITHUB_FLOW.md

The docs reference `github.properties`, which should be `gradle.properties` (https://github.com/touchlab/KMMBridgeSKIETemplate/blob/main/gradle.properties).

Fix gradle.properties filename

---

kmmbridge/src/main/kotlin/dependencymanager/CocoapodsDependencyManager.kt

Issue: https://github.com/touchlab/KMMBridge/issues/224
Patches cocoapods dependency manager curl header for use on self-hosted runners with different curl versions.
Followed @TadeasKriz suggestion of adding double quotes around `["'Accept: application/octet-stream'"]`
- `./gradlew test` PASSED
- `./gradlew build` PASSED
- manual testing PASSED 
We deployed a 0.3.8-SNAPSHOT from my fork to maven local and used it in our project on our self-hosted runner.  The curl command worked and pod lib lint was successful.   Please let me know if you have any questions.  Thanks!

double quotes around cocoapods curl header

---

kmmbridge/src/main/kotlin/KmmBridgeExtension.kt
kmmbridge/src/main/kotlin/artifactmanager/MavenPublishArtifactManager.kt

Wanted ability to adjust the `-kmmbridge` suffix that was being appended to artifacts when published to a Maven repo.
- Added optional parameter `artifactSuffix` to `MavenPublishArtifactManager` constructor and used it, if present, when setting `kmmbridgeArtifactId`
- Also added check for the optional parameter `publicationName` when creating the MavenPublication object
- `./gradlew test`
- `./gradlew build`
- manual testing

Add option for a custom suffix on Maven artifact names

---

kmmbridge/src/main/kotlin/BuildFileHelper.kt
kmmbridge/src/main/kotlin/co/touchlab/faktory/internal/GitLabApi.kt

Issue: https://github.com/touchlab/KMMBridge/issues/249
The GitLab domain in the Maven config is fixed to gitlab.com and can't be configured for self-hosted e.g. gitlab.companyname.com
* The GitLab domain can now be specified by optionally setting the `GITLAB_DOMAIN` property which is necessary if you need to publish to a self-managed instance.
* Corrected minor casing typos.
* Added logging of exception for easier problem diagnosis when there's an issue with the GitLab repo settings.
- `./gradlew test`
- `./gradlew build`
- manual testing

Extended GitLab Publishing for self managed instances #249

---

gradle.properties
kmmbridge/src/main/kotlin/co/touchlab/faktory/KmmBridgeExtension.kt
kmmbridge/src/main/kotlin/co/touchlab/faktory/dependencymanager/SpmDependencyManager.kt
kmmbridge/src/test/kotlin/co/touchlab/faktory/dependencyManager/PackageFileUpdateTest.kt

Issue: https://github.com/touchlab/KMMBridge/issues/168
- We must support having multiple framework declarations in the same Package.swift file
- Created an extra property to the SPM configuration called `perModuleVariablesBlock`
- This parameter works together with the `useCustomPackageFile`
- When it's set to true, each configuration block will mention the package name it's publishing so it knows which block should be updated.
- Check `withMultipleModules` test case
- `./gradlew test`
- `./gradlew build`

Allowing multiple packages in the same package.swift file

---

.github/workflows/release.yml

This was replaced in the vanniktech plugin as of 0.28.0 https://vanniktech.github.io/gradle-maven-publish-plugin/changelog/#0280-2024-03-12
Fixes the _apparent_ release action failures e.g. https://github.com/touchlab/KMMBridge/actions/runs/10689342756/job/29631221033

Use `releaseRepository` in release action

---

gradle.properties
kmmbridge/src/main/kotlin/co/touchlab/kmmbridge/KMMBridge.kt
kmmbridge/src/main/kotlin/co/touchlab/kmmbridge/KmmBridgeExtension.kt

Add Gradle param to support setting native build type from the command line. Allows for simpler build CI workflows for development.

Read parameter to set default native build type

---

kmmbridge/src/main/kotlin/co/touchlab/kmmbridge/dependencymanager/CocoapodsDependencyManager.kt

Issue: https://github.com/touchlab/KMMBridge/issues/267
Moving pod calls to use a ValueSource.
* Using a ValueSource instead
* If there's an `exitValue` error, we catch it and then throw the underlying error
* Some formatting
- `./gradlew test`
- `./gradlew build`
- manual testing
before
```
> Task :allshared:pushRemotePodspec FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':allshared:pushRemotePodspec'.
> Process 'command 'pod'' finished with non-zero exit value 1
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':allshared:pushRemotePodspec'.
Caused by: …
```

Use ValueSource to run pod commands for CocoaPods publishing
